# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starwars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starwars
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod "Resolver"

  target 'StarwarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarwarsUITests' do
    # Pods for testing
  end

end
